spring.thymeleaf.cache=false
spring.web.resources.cache.cachecontrol.no-store=true
spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.aqyduzeoeugvpwnefvxb
spring.datasource.password=YcbY4XZxbndN1z7u
spring.datasource.hikari.maximum-pool-size=5
